<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Resep;

class ResepSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id' => 2,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Burger Sapi 1',
                'produk_id' => 37,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 1',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 3,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Burger Sapi 2',
                'produk_id' => 38,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 2',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 4,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Hotdog Sosis Ayam',
                'produk_id' => 35,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis ayam',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 5,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Hotdog Sosis Sapi',
                'produk_id' => 36,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis Sapi',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 6,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Kentang Goreng',
                'produk_id' => 39,
                'deskripsi' => 'Resep untuk membuat Kentang Goreng',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 7,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Coca Cola',
                'produk_id' => 40,
                'deskripsi' => 'Resep untuk membuat Coca cola',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 8,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Sprite',
                'produk_id' => 41,
                'deskripsi' => 'Resep untuk membuat Sprite',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 9,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Paket A',
                'produk_id' => 49,
                'deskripsi' => 'Resep untuk membuat Paket A',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 10,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Paket B',
                'produk_id' => 50,
                'deskripsi' => 'Resep untuk membuat Paket B',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 11,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Paket C',
                'produk_id' => 51,
                'deskripsi' => 'Resep untuk membuat Paket C',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 12,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Burger Sapi 1',
                'produk_id' => 52,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 1',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 13,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Burger Sapi 2',
                'produk_id' => 53,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 2',
                'created_at' => '2025-11-18 11:25:21',
                'updated_at' => '2025-11-18 11:25:21',
            ],
            [
                'id' => 14,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Hotdog Sosis Ayam',
                'produk_id' => 54,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis Ayam',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 15,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Hotdog Sosis Sapi',
                'produk_id' => 55,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis Sapi',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 16,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Kentang Goreng',
                'produk_id' => 56,
                'deskripsi' => 'Resep untuk membuat Kentang Goreng',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 17,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Coca Cola',
                'produk_id' => 57,
                'deskripsi' => 'Resep untuk membuat Coca Cola',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 18,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Sprite',
                'produk_id' => 58,
                'deskripsi' => 'Resep untuk membuat Sprite',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 19,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Paket A',
                'produk_id' => 59,
                'deskripsi' => 'Resep untuk membuat Paket A',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 20,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Paket B',
                'produk_id' => 60,
                'deskripsi' => 'Resep untuk membuat Paket B',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 21,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Paket C',
                'produk_id' => 61,
                'deskripsi' => 'Resep untuk membuat Paket C',
                'created_at' => '2025-11-18 11:25:22',
                'updated_at' => '2025-11-18 11:25:22',
            ],
            [
                'id' => 22,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Burger Sapi 1',
                'produk_id' => 37,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 1',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 23,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Burger Sapi 2',
                'produk_id' => 38,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 2',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 24,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Hotdog Sosis Ayam',
                'produk_id' => 35,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis ayam',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 25,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Hotdog Sosis Sapi',
                'produk_id' => 36,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis Sapi',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 26,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Kentang Goreng',
                'produk_id' => 39,
                'deskripsi' => 'Resep untuk membuat Kentang Goreng',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 27,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Coca Cola',
                'produk_id' => 40,
                'deskripsi' => 'Resep untuk membuat Coca cola',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 28,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Sprite',
                'produk_id' => 41,
                'deskripsi' => 'Resep untuk membuat Sprite',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 29,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Paket A',
                'produk_id' => 49,
                'deskripsi' => 'Resep untuk membuat Paket A',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 30,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Paket B',
                'produk_id' => 50,
                'deskripsi' => 'Resep untuk membuat Paket B',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 31,
                'id_cabang' => 1,
                'nama_resep' => 'Resep Paket C',
                'produk_id' => 51,
                'deskripsi' => 'Resep untuk membuat Paket C',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 32,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Burger Sapi 1',
                'produk_id' => 52,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 1',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 33,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Burger Sapi 2',
                'produk_id' => 53,
                'deskripsi' => 'Resep untuk membuat Burger Sapi 2',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 34,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Hotdog Sosis Ayam',
                'produk_id' => 54,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis Ayam',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 35,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Hotdog Sosis Sapi',
                'produk_id' => 55,
                'deskripsi' => 'Resep untuk membuat Hotdog Sosis Sapi',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 36,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Kentang Goreng',
                'produk_id' => 56,
                'deskripsi' => 'Resep untuk membuat Kentang Goreng',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 37,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Coca Cola',
                'produk_id' => 57,
                'deskripsi' => 'Resep untuk membuat Coca Cola',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 38,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Sprite',
                'produk_id' => 58,
                'deskripsi' => 'Resep untuk membuat Sprite',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 39,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Paket A',
                'produk_id' => 59,
                'deskripsi' => 'Resep untuk membuat Paket A',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 40,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Paket B',
                'produk_id' => 60,
                'deskripsi' => 'Resep untuk membuat Paket B',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
            [
                'id' => 41,
                'id_cabang' => 2,
                'nama_resep' => 'Resep Paket C',
                'produk_id' => 61,
                'deskripsi' => 'Resep untuk membuat Paket C',
                'created_at' => '2025-11-18 11:25:29',
                'updated_at' => '2025-11-18 11:25:29',
            ],
        ];

        foreach ($data as $item) {
            Resep::updateOrCreate(
                ['id' => $item['id']],
                $item
            );
        }

        $this->command->info('Resep berhasil di-seed!');
    }
}
